### ISSUE TITLE
Inference with single image

### ISSUE THREAD

**Issue by phexic** [shahrukhqasim/TIES-2.0#18]
@shahrukhqasim hi, i have a question after reading your code. When inferring a picture, do we need to provide a box corordinate(x,y,x2,y2) for each word in the table? Because i did not see any updatas about vertex features in your code.

**Comment by phexic** [comment]
@shahrukhqasim

**Comment by iamrishab** [comment]
I want to parse the detected table for recognition or information retrieval. For that, I have the (x1,y1,x2,y2) of the detected table. Have you solved this problem?

**Comment by kmanojkkmr** [comment]
Hello @iamrishab ,

I am also looking for the same. I have detected table and have it's BBox coordinates. Now I am looking for table recognition and extract data from it. Did you solve this?

Thank you in advance. :)
