### ISSUE TITLE
What is the "config" argument in `table_adjacency_parsing.py` ?

### ISSUE THREAD

**Issue by munikarmanish** [shahrukhqasim/TIES-2.0#4]
I followed all the steps you mentioned in the README to train/test the model:

```
(ties) manish@gpu:~/code/TIES-2.0/python$ python bin/iterate/table_adjacency_parsing.py ../configs/config.ini config
Traceback (most recent call last):
  File "bin/iterate/table_adjacency_parsing.py", line 20, in <module>
    gconfig.init(args.input, args.config)
  File "/home/manish/code/TIES-2.0/python/libs/configuration_manager.py", line 17, in init
    config_manager_instance = ConfigurationManager(config_file_path, config_name)
  File "/home/manish/code/TIES-2.0/python/libs/configuration_manager.py", line 10, in __init__
    self.config = config_file[config_name]
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'config'
```

I looked at the help output:
```
usage: table_adjacency_parsing.py [-h] [--test TEST] [--profile PROFILE] [--visualize VISUALIZE] input config
table_adjacency_parsing.py: error: the following arguments are required: input, config
```

I couldn't figure out what are the `input` and `config` arguments for the script. Any help would be highly appreciated!

Useful system info:
- Python version: 3.5
- OS: Ubuntu 16.04

**Comment by shahrukhqasim** [comment]
It is the section in the config file. Check details here:
[https://en.wikipedia.org/wiki/INI_file](https://en.wikipedia.org/wiki/INI_file)

**Comment by dexterslabs** [comment]
if you are using config.ini.example, you can use the following params
`table_adjacency_parsing.py configs/config.ini basic_conv_graph`

**Comment by ReikoMin** [comment]
@munikarmanish Have you solved this problem so far? I also met the same problem,thanks
