### ISSUE TITLE
Regarding parsing error

### ISSUE THREAD

**Issue by dexterslabs** [shahrukhqasim/TIES-2.0#7]
Thanks for making the code available for the paper. I am running the code with the example data you provided. I am running in to error related to parsing.
```
iterators/table_adjacency_parsing_iterator.py", line 78, in train
    model.sanity_preplot(sess, summary_writer)

tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: global_features.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}} = ParseSingleExample[Tdense=[DT_INT64, DT_INT64, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], dense_keys=["adjacency_matrix_cells", "adjacency_matrix_cols", "adjacency_matrix_rows", "global_features", "image", "vertex_features", "vertex_text"], dense_shapes=[[810000], [810000], [810000], [3], [1049088], [4500], [27000]], num_sparse=0, sparse_keys=[], sparse_types=[]](arg0, ParseSingleExample/Const, ParseSingleExample/Const, ParseSingleExample/Const, ParseSingleExample/Const_3, ParseSingleExample/Const_3, ParseSingleExample/Const_3, ParseSingleExample/Const)]]
	 [[node IteratorGetNext_1 (defined at /table_detection/graphparsing/ties_v2/readers/image_words_reader.py:67)  = IteratorGetNext[output_shapes=[[?,4500], [?,27000], [?,1049088], [?,3], [?,810000], [?,810000], [?,810000]], output_types=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_INT64, DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_1)]]
	 [[{{node IteratorGetNext_1/_9}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_11_IteratorGetNext_1", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

I think the issue  is related to getfeeds. I think there is mismatch between how TFRecords are packed and how they are parsed. I also tried by generating new data using the code provided in READ file and I am facing the same issue.

**Comment by dexterslabs** [comment]
Changing 
```
; Number of total global features
num_global_features=4

; Unknown? (remove it next time)
num_data_dims=5

```

**Comment by munikarmanish** [comment]
I had the same issue. That particular error was gone after changing the variables in the config (as mentioned above). However, now the program **segfaults** after one iteration.

```
...
Starting iterations
Training Iteration 0:
Accuracy - cells: 0.500672102 rows: 0.487090439 cols: 0.495236427 
 Loss     - cells: 0.694381773 rows: 0.72147584 cols: 0.726865649 
 Fraction - cells: 0.493346483 rows: 0.514542282 cols: 0.504710674 
 Total loss: 0.72147584
---------------------------------------------------
Validation Iteration 0:
Accuracy - cells: 0.504660308 rows: 0.500964344 cols: 0.496350169 
 Loss     - cells: 0.692633688 rows: 0.709815621 cols: 0.721956372 
 Fraction - cells: 0.495503753 rows: 0.495069176 cols: 0.503972471 
 Total loss: 0.709815621
---------------------------------------------------
Visualizing
Training Iteration 1:
Accuracy - cells: 0.495369285 rows: 0.498303801 cols: 0.499932796 
 Loss     - cells: 0.692240357 rows: 0.711595178 cols: 0.726988494 
 Fraction - cells: 0.504212081 rows: 0.496714324 cols: 0.500122249 
 Total loss: 0.711595178
Segmentation fault (core dumped)
```

@dexterslabs Did you encounter this? What do you think could be the reason for this segfault?

**Comment by shahrukhqasim** [comment]
@dexterslabs Yes, you are right, global features are supposed to be four. That was causing the issue. I am using  the following configuration myself which works fine:
```
[gravnet_fast_conv_1]
from_scratch=1
is_sampling_balanced=1
batch_size=25
train_for_iterations=20000000000
learning_rate=0.0001
num_testing_samples=100
summary_path=/home/shahrukh/SundayOnwardOut/gravnet_fast_conv/summary
model_path=/home/shahrukh/SundayOnwardOut/gravnet_fast_conv/model
test_out_path=/home/shahrukh/SundayOnwardOut/gravnet_fast_conv/test

training_files_list=/home/hassanmahmood/tukldataset/train_files.txt
validation_files_list=/home/hassanmahmood/tukldataset/validate_files.txt
test_files_list=/home/hassanmahmood/tukldataset/test_files.txt

model=conv_grav_net_fast_conv
profiler_output_file_name=/home/shahrukh/SundayOnwardOut/gravnet_fast_conv/profiler
visual_feedback_out_path=/home/shahrukh/SundayOnwardOut/gravnet_fast_conv/visual_feedback
max_vertices=900
num_vertex_features=5
max_image_height=768
max_image_width=1366
image_channels=1
max_words_len=30
dim_vertex_x_position=0
dim_vertex_y_position=1
dim_vertex_x2_position=2
dim_vertex_y2_position=3
dim_num_vertices=2
num_global_features=4
dim_width=1
dim_height=0
num_data_dims=3
variable_scope=conv_grav_net_fast_conv_1
samples_per_vertex=6
loss_alpha=1
loss_beta=1
loss_gamma=1
save_after_iterations=50
validate_after=100
visualize_validation_results_after=150
```

@munikarmanish I am not sure about the segmentation fault. Have you managed to resolve it yet?

**Comment by munikarmanish** [comment]
@shahrukhqasim When using _your_ config, the training ran for about 300 iterations and then **segfault**ed again! Could this be caused by insufficient memory? By the way, one interesting thing I noticed is that one of `row` and `cell` accuracies never reached more than ≈50% while the other two went up to 98%.

Also, what is the "Fraction" in the output?

```
Training Iteration 319:
 Accuracy - cells: 0.986933231 rows: 0.975857377 cols: 0.494874418 
 Loss     - cells: 0.0397053286 rows: 0.213991225 cols: 0.420835525 
 Fraction - cells: 0.504426718 rows: 0.500666559 cols: 0.505125642 
 Total loss: 0.224844024
```

Finally, how to use the saved model in "inference" mode? For instance, I want to send an image of a table along with the text blocks (from OCR). Is there a way to get the 3 matrices from these inputs?

**Comment by shahrukhqasim** [comment]
@munikarmanish `fraction` was for debugging purposes as an estimate of classes distribution. It shows: class 0/(class 0 + class 1) fraction averaged over all the vertices and over the batch.

Yeah, I think it could be something related to memory; however, normally, TensorFlow throws a memory exception. I'll run again tonight to see if I am getting it. It was working fine last time I worked with this repository.

**Comment by hasslercastro** [comment]
@munikarmanish  
Did you get better results ?
Did you generate a synthetic dataset provided, if so, how many images did you save per record?

**Comment by munikarmanish** [comment]
@hasslercastro Yes, I generated the synthetic dataset, and I noticed that it didn't have enough variations—same font, always 2 header rows, same alignment for all columns, similar shapes, etc.

**Comment by hasslercastro** [comment]
@munikarmanish Ah okay, did you try with your own dataset?

**Comment by parzival1l** [comment]
@munikarmanish where you able to figure out how to send a image with OCR textblocks and get the 3 adj matrics.

**Comment by ashish-kubade** [comment]
@munikarmanish how did you resolve the segfaults issue. I am facing the same error and my GPU memory, for sure, is not exhausting as I am using very small batch size. nvidia-smi shows, 1200 MB/ 24GBs only
