### ISSUE TITLE
Cols loss remains same over the iterations

### ISSUE THREAD

**Issue by dexterslabs** [shahrukhqasim/TIES-2.0#8]
The code is working great for rows and cells. However, the cols are not getting optimized. I tried to shift my focus exclusively on cols by having the following config. 
```
; Weight of losses, for cells, rows and cols respectively
; No need to sum it to one, will be handled internally (could be floating points)
loss_alpha=0
loss_beta=0
loss_gamma=4
```

However, I see there is no much change in accuracy or loss for cols. I am missing something? 
```
Training Iteration 2041:
Accuracy - cells: 0.41997537 rows: 0.488680273 cols: 0.508866429
 Loss     - cells: 0.740955174 rows: 0.861711681 cols: 0.533341587
 Fraction - cells: 0.500545442 rows: 0.492519379 cols: 0.49120307
 Total loss: 0.533341587
```

**Comment by shahrukhqasim** [comment]
It is normal and takes a while. I see that it has taken you over 2000 iterations. Did it work eventually?

**Comment by dexterslabs** [comment]
Yup. A steep curve all of a sudden after 2400 iterations. That’s why I closed this issue. Thanks for taking time :)

**Comment by jin-s13** [comment]
I have trained the network for over 20K iterations. The cell-loss and the row-loss is working fine but still the col loss is not decreasing...

Accuracy - cells: 1 rows: 0.999960303 cols: 0.505201817                 
 Loss     - cells: 0.000387156499 rows: 0.000397676224 cols: 0.693147182
 Fraction - cells: 0.497624427 rows: 0.50205797 cols: 0.494798213       
 Total loss: 0.231310666   

I use the config.ini which is modified from config.ini.example ['conv_graph_dgcnn_fast_conv']
`from_scratch=1
is_sampling_balanced=1
batch_size=25
loss_alpha=1
loss_beta=1
loss_gamma=1
`
Should I use larger loss_gamma?

**Comment by hasslercastro** [comment]
How does the visual feedback look like?

**Comment by jin-s13** [comment]
I visualize the loss curve using tensorboard. 
![snapshot10](https://user-images.githubusercontent.com/11788150/62995628-f5833f00-be93-11e9-85df-5f363012b335.png)

**Comment by hasslercastro** [comment]
@jin-s13 @dexterslabs any of you guys tried to test the trained model with another image, I mean a table outside the generated ones ? if so, how did  you manage to transform the image to a compatible tf_record to run on inference.
